"""Nebula generation engine.

A model-agnostic content core. It ships with a deterministic, pure-Python
writer so the product is fully usable with zero API keys; when a provider key
is configured (``NEBULA_LLM_*`` env, see ``llm.py``) the same call shape is
used to upgrade drafts with a real model.

Kinds:
    blog      long-form article + outline + meta description
    text      short-form copy (email / ad / product / script / launch note)
    caption   platform-aware social captions
    rewrite   tone + conciseness rewriting with a change log
    summarize extractive summary, key points, action items
    seo       keyword expansion, intent, optimisation brief
    analyze   content analyzer: readability, AI-tell score, tone, fixes
"""
from __future__ import annotations

import math
import re
from typing import Any

from . import nlp
from .nlp import band, dice, key_terms, log_scale, pick, readability, title_case, tokenize

YEAR = 2026

# ------------------------------------------------------------------ lexicons
AI_FLAGS = {
    "overused": ["delve", "navigate", "landscape", "seamless", "unlock", "leverage", "elevate",
                 "robust", "testament", "foster", "harness", "paradigm", "unveil", "crucial",
                 "pivotal", "multifaceted", "holistic", "synergy", "imperative", "transformative",
                 "myriad", "embark", "game-changer"],
    "connectives": ["moreover", "furthermore", "additionally", "in conclusion", "overall",
                    "consequently", "nevertheless", "that said", "it is worth noting",
                    "in today's fast-paced", "when it comes to"],
    "openers": ["in the world of", "in today's", "it's important to note", "let's face it",
                "at the end of the day", "whether you're", "look no further"],
}

POSITIVE = set("great excellent strong clear fast love helpful useful best win grow boost easy smooth improve better".split())
NEGATIVE = set("slow hard broken bad worst fail loss weak messy unclear painful buggy expensive late confusing risk".split())

TONE_BANKS: dict[str, dict[str, Any]] = {
    "professional": {
        "open": ["The short version:", "Here is where it matters:", "Practically speaking,"],
        "verb": {"get": "obtain", "buy": "purchase", "start": "initiate", "help": "support",
                 "big": "substantial", "fix": "resolve", "check": "review", "show": "demonstrate"},
        "close": "Happy to walk through the detail on a call if that is useful.",
    },
    "casual": {
        "open": ["Okay so -", "Real talk:", "Quick one:"],
        "verb": {"obtain": "get", "purchase": "grab", "initiate": "kick off", "utilize": "use",
                 "demonstrate": "show", "substantial": "big", "resolve": "fix"},
        "close": "That's the whole trick of it.",
    },
    "bold": {
        "open": ["Stop guessing.", "Most teams get this wrong.", "Here is the uncomfortable part:"],
        "verb": {"try": "commit to", "help": "force", "maybe": "will", "aim to": "ship"},
        "close": "Decide today. The compounding starts either way.",
    },
    "friendly": {
        "open": ["Good news -", "You're closer than you think.", "Let's make this easy:"],
        "verb": {"must": "want to", "required": "handy", "execute": "run"},
        "close": "Rooting for you - start small and iterate.",
    },
    "witty": {
        "open": ["Plot twist:", "Nobody tells you this, but", "In theory - only in theory -"],
        "verb": {"improve": "make less painful", "optimize": "stop doing the dumb version of"},
        "close": "If that is not motivation, I'll rename the file again.",
    },
    "urgent": {
        "open": ["This is time-boxed:", "Do it before Friday:", "One window, then it shuts:"],
        "verb": {"later": "now", "soon": "today", "consider": "move on"},
        "close": "Doors close Friday 18:00 - after that you are on the waitlist.",
    },
}

FILLER_RE = re.compile(
    r"\b(?:it is (?:important|worth noting) to note that|needless to say|at the end of the day|"
    r"when it comes to|in today.s (?:fast-paced |digital )?(?:world|landscape)?|"
    r"due to the fact that|it goes without saying|in this article we will)[,:\s]*",
    re.I,
)

JUNK_LINE = re.compile(
    r"^(generated by|analysed|read time|who this is for|keywords?:|export|\u00a9|compressed|tone:|language:|step \d|.*\|.*\|)", re.I,
)

PLATFORMS = {
    "instagram": {"max": 2200, "tags": (5, 9), "emoji": 2},
    "linkedin": {"max": 1300, "tags": (3, 5), "emoji": 0},
    "x": {"max": 275, "tags": (1, 2), "emoji": 1},
    "tiktok": {"max": 300, "tags": (3, 5), "emoji": 3},
    "facebook": {"max": 480, "tags": (1, 3), "emoji": 1},
    "threads": {"max": 500, "tags": (0, 2), "emoji": 1},
    "youtube": {"max": 400, "tags": (3, 6), "emoji": 1},
}

WORD_SWAPS = {
    "utilize": "use", "leverage": "use", "facilitate": "help", "methodology": "method",
    "prioritize": "focus on", "synergy": "teamwork", "holistic": "complete",
    "paradigm": "model", "innovative": "new", "robust": "solid", "seamlessly": "smoothly",
    "in order to": "to", "at this point in time": "now", "due to the fact that": "because",
}

BLOG_SPINE = [
    ("Why this matters now", "why"),
    ("What the shift really is", "what"),
    ("The 4-step workflow", "how"),
    ("Where teams get stuck", "problems"),
    ("Tools, templates and numbers", "tools"),
    ("Mistakes to avoid", "mistakes"),
    ("What to do this week", "action"),
]

FAQ_TEMPLATES = ["What is {topic} in simple terms?", "How long does {topic} take to show results?",
                 "Do I need special tooling to start?", "Is {topic} still worth doing in {year}?",
                 "What does a good example look like?"]

TOOLS = ["a shared brief template", "a 90-day content calendar", "a one-pass AI draft",
         "a review checklist", "a measurement dashboard", "a prompt library"]

EMOJIS = ["🚀", "📈", "🧠", "✨", "🔁", "⏱️", "👀", "🧩", "🎯"]


# ---------------------------------------------------------------- utilities
_SENT_START = re.compile(r"(^|(?<=[.!?])\s+|\n\s*)([a-z])", re.M)


def _recap(text: str) -> str:
    """Capitalise sentence/line starts, skipping URLs and inline labels."""
    def rep(m: re.Match) -> str:
        ch = m.group(2)
        tail = text[m.end():m.end() + 12]
        if re.match(r"^[a-z0-9.-]*://", tail) or re.match(r"^[a-z0-9.-]*\.[a-z]{2,}/", tail):
            return m.group(0)
        return m.group(1) + ch.upper()
    return _SENT_START.sub(rep, text)


def _clean_fluff(text: str) -> str:
    out = text or ""
    for bad, good in WORD_SWAPS.items():
        out = re.sub(r"\b" + re.escape(bad) + r"\b", good, out, flags=re.I)
    out = re.sub(r"\s+([,.;:!?])", r"\1", out)
    out = re.sub(r"[ \t]{2,}", " ", out)
    out = _recap(out)
    out = nlp.fix_articles(out)
    out = re.sub(r"[ \t]{2,}", " ", out)
    return out.strip()


def _len_words(length: str) -> int:
    return {"tiny": 90, "short": 180, "medium": 420, "long": 800, "epic": 1400}.get(length, 420)


def _norm(params: dict) -> dict:
    prompt = (params.get("prompt") or "").strip()
    return {
        "prompt": prompt,
        "topic": nlp.topic_of(prompt) or "your topic",
        "tone": params.get("tone") or "professional",
        "audience": params.get("audience") or "busy operators",
        "length": params.get("length") or "medium",
        "language": params.get("language") or "English",
        "keywords": [str(k).strip().lower() for k in (params.get("keywords") or []) if str(k).strip()],
        "source": params.get("source") or prompt,
        "brand": params.get("brand") or "Nebula Studio",
        "format": params.get("format") or "email",
        "platforms": params.get("platforms") or [],
        "mode": params.get("mode") or "tone",
        "contact": params.get("contact") or "",
        "salt": str(params.get("salt") or "v1"),
    }


def _paragraph(ctx: dict, section: str, idx: int, n_sentences: int) -> str:
    """claim -> mechanism -> proof -> consequence, phrased per section."""
    topic, audience = ctx["topic"], ctx["audience"]
    kws = ctx["keywords"] or [topic]
    kw = kws[idx % len(kws)]
    bank = {
        "why": [
            "Most {aud} do not lose to competitors on {topic} - they lose to their own handoffs.".format(aud=audience, topic=topic),
            "The cost of sloppy {kw} shows up two quarters later as pipeline nobody can explain.".format(kw=kw),
            "Teams that run {topic} as a written process ship {a}.{b}x more output with the same headcount.".format(topic=topic, a=band(ctx["salt"], 2, 5), b=band(section, 1, 9)),
            "There is a boring reason {kw} stalls: nobody wrote down who decides.".format(kw=kw),
        ],
        "what": [
            "At its simplest, {topic} is the loop between a brief, a draft, a review and a publish date.".format(topic=topic),
            "Strip the jargon and {kw} means one thing: a repeatable way to turn intent into finished copy.".format(kw=kw),
            "A {topic} system has three moving parts - inputs, an editor with taste, and one home for everything.".format(topic=topic),
            "Where {kw} usually fails is scope: every step assumes someone else owns the last one.".format(kw=kw),
        ],
        "how": [
            "Start from the outcome, written at the top of the brief, then delete every line that does not serve it.",
            "Generate {n} drafts against that same brief and merge the strongest paragraphs instead of picking a favourite.".format(n=band(ctx["salt"], 2, 4)),
            "Read it aloud. If a sentence needs a second breath, split it in two.",
            "Publish to {where}, then repurpose once - not before.".format(where=pick(["one channel", "two channels", "the newsletter first"], section)),
        ],
        "problems": [
            "The classic failure with {topic} is the blank-page tax: {m} minutes lost before the first sentence.".format(topic=topic, m=band(section, 20, 65)),
            "Review is where {kw} dies - one reviewer rewrites tone, the next rewrites structure, and nothing ships.".format(kw=kw),
            "Version drift is quiet and expensive: three drafts of the same post, two live links, zero owners.",
            "Volume without a template set turns {kw} into re-litigation.".format(kw=kw),
        ],
        "tools": [
            "We run {topic} on {tool}, because the tool matters far less than the constraint.".format(topic=topic, tool=pick(TOOLS, ctx["salt"])),
            "A {n}-field brief beats any prompt library: context is the multiplier for {kw}.".format(n=band(ctx["salt"], 4, 9), kw=kw),
            "Measure {m} weekly and ignore the vanity metrics.".format(m=pick(["time-to-first-draft", "publish cadence", "edits per piece", "organic lift"], section)),
            "Automate the handoff, never the judgement - that is the whole {topic} trick.".format(topic=topic),
        ],
        "mistakes": [
            "Do not publish {topic} content that explains the industry to people who already live in it.".format(topic=topic),
            "Skipping the {kw} outline costs more than it saves: about {p}% of the draft ends up unused.".format(kw=kw, p=band(section, 10, 40)),
            "Never edit the same draft twice without a fresh pair of eyes.",
            "Deleting the numbers is how a strong post turns into a vague one.",
        ],
        "action": [
            "This week: rebuild {pick} against this {topic} checklist.".format(pick=pick(["the best-performing post", "the deadest campaign", "next month's first send"], section), topic=topic),
            "Give {kw} one owner and a 15-minute daily review window. That is the entire change.".format(kw=kw),
            "Ship the smallest version, keep the scorecard, expand only what survives.",
            "Write tomorrow's brief today - {a} minutes now buy back {b} hours next week.".format(a=band(ctx["salt"], 2, 6), b=band(section, 3, 9)),
        ],
    }.get(section, [])
    if not bank:
        return ""
    lines: list[str] = []
    i = int(dice(ctx["salt"], section) * len(bank))
    while len(lines) < n_sentences and i < len(bank) * 3:
        cand = bank[i % len(bank)]
        if cand and cand not in lines:
            lines.append(cand)
        i += 1
    tone = TONE_BANKS.get(ctx["tone"], TONE_BANKS["professional"])
    body = " ".join(lines)
    if idx == 0 and tone.get("open"):
        body = pick(tone["open"], ctx["salt"], section) + " " + body
    return body


# --------------------------------------------------------------------- blog
NOISE_WORDS = nlp.CONTENT_TYPE_WORDS | nlp.AUDIENCE_WORDS


def _keywords(ctx: dict) -> list[str]:
    """Keyword list for an article: the topic first, then real phrases from the
    brief, minus content-type and audience noise that would read as a subject."""
    out = [ctx["topic"]]
    for kw in ctx["keywords"] or []:
        if kw.lower() not in [o.lower() for o in out]:
            out.append(kw)
    for item in nlp.ngrams(ctx["prompt"], (1, 3), 14):
        phrase = item["phrase"]
        toks = tokenize(phrase)
        if not toks or all(t in NOISE_WORDS for t in toks):
            continue
        if all(w in ctx["topic"].lower() for w in toks):
            continue  # already covered by the topic itself
        if phrase.lower() in [o.lower() for o in out]:
            continue
        out.append(phrase)
    return [nlp.fix_acronyms(k) for k in out[:8]]


def blog(ctx: dict) -> dict:
    target = _len_words(ctx["length"])
    kws = _keywords(ctx)
    n_sections = 3 if target <= 200 else 4 if target <= 300 else 5 if target <= 700 else 7
    sections = BLOG_SPINE[:n_sections]
    topic, brand, salt = ctx["topic"], ctx["brand"], ctx["salt"]
    tone = TONE_BANKS.get(ctx["tone"], TONE_BANKS["professional"])

    hook = pick([
        "{t} is not a creative problem. It is a systems problem with a word count.".format(t=title_case(topic)),
        "Nobody wakes up excited to write about {topic}. That is exactly why the process has to be boring.".format(topic=topic),
        "You can publish more, or you can publish faster. {t} only moves the needle when it is both.".format(t=title_case(topic)),
    ], salt, "hook")

    title = pick([
        "{t}: A Field Guide for {a}".format(t=title_case(topic), a=title_case(ctx["audience"])),
        "How to Do {t} Without Burning the Team Out".format(t=title_case(topic)),
        "{t} in {y}: {n} Steps That Actually Ship".format(t=title_case(topic), y=YEAR, n=band(salt, 5, 9)),
        "The {t} Playbook ({y} Edition)".format(t=title_case(topic), y=YEAR),
    ], salt, "title")
    meta_desc = "{t} for {a}: {n} steps, real numbers and copy-paste templates. {y} guide by {b}.".format(
        t=title_case(topic), a=ctx["audience"], n=n_sections, y=YEAR, b=brand)

    blocks: list[str] = ["# " + title, "", "_" + meta_desc + "_", "", hook, "",
                         "**Who this is for:** {a} who need more {t} output without extra headcount.".format(a=ctx["audience"], t=topic),
                         "**Read time:** {m} min | **Tone:** {tone} | **Language:** {lang}".format(
                             m=max(2, round(target / 225)), tone=ctx["tone"], lang=ctx["language"]),
                         ""]
    for i, (heading, key) in enumerate(sections):
        blocks.append("## " + title_case(heading.replace("{topic}", topic)))
        blocks.append("")
        if key == "how":
            steps = ["Write a 6-field brief: outcome, audience, angle, proof, keywords, CTA.",
                     "Generate three drafts against that brief, then merge the best paragraphs.",
                     "Cut 30 percent - adjectives, throat-clearing openers, anything without a number.",
                     "Publish, then score it every Friday on replies that mention buying."]
            labels = ["Brief", "Draft", "Cut", "Ship"]
            for step, (label, line) in enumerate(zip(labels, steps), start=1):
                blocks.append("{}. **{}** - {}".format(step, label, line))
            blocks.append("")
        blocks.append(_paragraph(dict(ctx, keywords=kws), key, i, 4 if key in ("why", "how", "tools") else 3))
        blocks.append("")
        if key == "tools":
            blocks.append("| Lever | Before | After |")
            blocks.append("| --- | --- | --- |")
            blocks.append("| Brief to draft | {} days | same day |".format(band(salt, 3, 6)))
            blocks.append("| Draft to publish | {} days | {} days |".format(band(salt, 4, 9), band(salt, 1, 2)))
            blocks.append("| Edits per piece | {} | {} |".format(band(salt, 6, 14), band(salt, 1, 3)))
            blocks.append("")
        if key == "problems":
            blocks.append("> If you fix only one thing, fix the brief. No shared definition of done turns {t} into taste.".format(t=topic))
            blocks.append("")

    blocks.append("## FAQ")
    blocks.append("")
    faq_answers = ["Usually {n} weeks, if the brief and review steps hold.".format(n=band(salt, 2, 8)),
                   "No. Start with one template and one channel; add tooling once the habit exists.",
                   "Yes - {t} rewards consistency more than talent.".format(t=topic),
                   "A good one shows the change: what you did, the number it moved, what you would cut."]
    for qi, q in enumerate(FAQ_TEMPLATES[:3]):
        blocks.append("**" + q.format(topic=topic, year=YEAR) + "**")
        blocks.append("")
        blocks.append(faq_answers[qi % len(faq_answers)])
        blocks.append("")
    blocks += ["## The bottom line",
               "Make {t} repeatable before you make it clever. One brief, one owner, one number to beat. {c}".format(t=topic, c=tone["close"]),
               "",
               "_Generated by {b} | keywords: {k}_".format(b=brand, k=", ".join(kws[:5]))]
    content = _clean_fluff("\n".join(blocks))
    stats = readability(content)
    return {
        "title": title,
        "content": content,
        "meta": {
            "meta_description": meta_desc.strip()[:158],
            "outline": [title_case(h) for h, _ in sections],
            "keywords": kws[:6],
            "word_count": stats["words"],
            "target_words": target,
            "reading_time_min": stats["reading_time_min"],
            "sections": n_sections,
            "readability": stats["flesch"],
        },
    }


# --------------------------------------------------------------------- text
def text(ctx: dict) -> dict:
    fmt = str(ctx.get("format") or "email").lower()
    topic, brand, salt = ctx["topic"], ctx["brand"], ctx["salt"]
    tone = TONE_BANKS.get(ctx["tone"], TONE_BANKS["professional"])
    title = "Draft - " + topic

    if fmt.startswith("product"):
        title = "{t} - product description".format(t=title_case(topic))
        body = (
            "**{t}.** Built for {a} who refuse to spend another week on manual content ops.\n\n"
            "Three things matter here: speed, review, proof. {t} handles all three - {x}x throughput, "
            "one approval lane, and a scorecard attached to every piece.\n\n"
            "- {b1}\n- {b2}\n- From ${p}/mo, cancel any month\n\n_{c}_").format(
            t=title_case(topic), a=ctx["audience"], x=band(salt, 3, 9),
            b1=pick(["Ships in minutes, not sprints", "Zero setup, real output", "Your tone, not the model's"], salt, 1),
            b2=pick(["One review lane, full version history", "Reuses your brief, not a generic prompt"], salt, 2),
            p=band(salt, 19, 79), c=tone["close"])
    elif fmt.startswith("ad"):
        title = "Ad copy - " + pick(["paid social", "search", "display"], salt)
        body = (
            "**{h}**\n\n{t} gives {a} a draft in {s} seconds: brief, generate, approve, ship. "
            "No prompt engineering degree required.\n\n- {p1}\n- {p2}\n\n-> {cta}. Cancel whenever.").format(
            h=pick(["Stop writing from scratch.", "Your content queue is a lie.", "Publish daily without a bigger team."], salt, 1),
            t=title_case(topic), a=ctx["audience"], s=band(salt, 8, 45),
            p1=pick(["Templates for blog, social, ads and email", "One workspace, one source of truth"], salt, 2),
            p2=pick(["Usage analytics tied to pipeline", "Export to Markdown, HTML or your CMS"], salt, 3),
            cta=pick(["Start free", "Try it for 14 days", "See it on your own brief"], salt, 4))
    elif fmt.startswith("script") or fmt.startswith("video"):
        title = "Short-form script - " + topic
        beats = [
            "**HOOK (0-3s)** - \"{h}\"".format(h=pick([
                "{t} takes 6 hours. Or 6 minutes. Here is the difference.".format(t=title_case(topic)),
                "Nobody in your Slack is going to save this post - and that is the problem."], salt)),
            "",
            "**PROBLEM (3-15s)** - {a} lose {n} hours a week to blank-page start-up cost.".format(a=ctx["audience"], n=band(salt, 3, 11)),
            "",
            "**MEAT (15-45s)** - {tool}. Three beats: brief, draft, review. Say the number out loud: {p}% more shipped.".format(
                tool=pick(TOOLS, salt), p=band(salt, 12, 40)),
            "",
            "**CTA (45-55s)** - \"{c}\"".format(c=tone["close"]),
            "",
            "_Runtime ~{r}s | 4 beats | captions on_".format(r=band(salt, 48, 62)),
        ]
        body = "\n".join(beats)
    elif fmt.startswith("announce") or fmt.startswith("launch"):
        title = "Launch note - " + topic
        body = (
            "### {t} is live\n\nWe shipped it. {l}: {a} can now go from brief to published in one place, "
            "with a review trail and a scorecard.\n\n**What you get**\n"
            "1. Drafts in your tone, on brief\n2. One workspace for text, image and social\n"
            "3. Usage analytics tied to outcomes\n\n_{c}_\n\n- {b}").format(
            t=title_case(topic), l=pick(["What this means for you", "Here is what changed", "The short version"], salt),
            a=ctx["audience"], c=tone["close"], b=brand)
    else:  # email
        greeting = str(ctx.get("contact") or "there").strip().split()[0] or "there"
        lead_open = pick(tone["open"], salt)
        if lead_open.endswith(("-",)):
            lead_open = lead_open.rstrip("-,") + "."
        subject = pick([
            "{t}: {n} ideas for {f} this week".format(t=title_case(topic), n=band(salt, 3, 7), f=ctx["audience"].split()[0]),
            "Quick one on {t}".format(t=topic),
            "{t} - before you plan next month".format(t=title_case(topic)),
        ], salt, "subject")
        title = subject
        body = (
            "Hi {name},\n\n{o} Most teams treat {t} as a writing task. It is really a routing task: brief in, "
            "three drafts out, one approved, one number attached.\n\n"
            "Here is the version we would run this week:\n"
            "1. Pick {p}.\n2. Re-brief it in 6 fields (outcome, audience, angle, proof, keywords, CTA).\n"
            "3. Generate {n} drafts and merge the top two.\n4. Cut 30 percent. Publish. Score it Friday.\n\n"
            "{c}\n\n- {b}").format(
            name=greeting, o=lead_open, t=topic,
            p=pick(["the best-performing post", "the deadest campaign", "the one everyone complains about"], salt, 2),
            n=band(salt, 3, 5), c=tone["close"], b=brand)

    body = _clean_fluff(body)
    stats = readability(body)
    out_meta = {"format": fmt, "tone": ctx["tone"], "word_count": stats["words"],
                "reading_time_min": stats["reading_time_min"], "readability": stats["flesch"]}
    if fmt.startswith("email") or fmt == "text":
        out_meta["subject_line"] = title
        out_meta["preview_text"] = re.sub(r"\s+", " ", body)[:104]
    return {"title": title, "content": body, "meta": out_meta}


# ------------------------------------------------------------------ captions
def caption(ctx: dict) -> dict:
    topic, salt = ctx["topic"], ctx["salt"]
    wanted = [p for p in (ctx.get("platforms") or ["instagram", "linkedin", "x"]) if p in PLATFORMS] or ["instagram"]
    hooks = [
        "{t} in {y} looks less like writing and more like editing.".format(t=title_case(topic), y=YEAR),
        "We cut {p}% of our {t} drafts last quarter. Output went up.".format(p=band(salt, 40, 80), t=topic),
        "Nobody shares a polished paragraph. They share a specific number.",
        "Hot take: {t} is 10 percent ideas and 90 percent shipping cadence.".format(t=topic),
        "If your {t} process needs a meeting to start, it is not a process.".format(t=topic),
    ]
    ctas = ["Save this for Monday.", "Comment \u201cBRIEF\u201d and I will send the template.",
            "Repost if it saved you an hour.", "Full breakdown on the blog.",
            "Tell me the one step you would delete."]
    opts = []
    for i, plat in enumerate(wanted):
        rule = PLATFORMS[plat]
        hook = pick(hooks, salt, plat, "h")
        compact = rule["max"] <= 500
        if compact:  # X / Threads / TikTok need a short post, not a trimmed long one
            body = "{h}".format(h=hook)
        else:
            body = (
                "{h}\n\nThe move for {a}: brief, {n} drafts, merge, cut 30 percent, ship. "
                "One number per post, or the post is a mood and not a metric.").format(
                h=hook, a=ctx["audience"], n=band(salt, 2, 4))
        if rule["emoji"]:
            body += " " + " ".join(pick(EMOJIS, plat, j) for j in range(rule["emoji"]))
        raw_tags = [topic, "contentops", "aiwriting", "marketing", "growth", "copywriting", ctx["tone"]]
        tags = ["#" + re.sub(r"[^a-z0-9]", "", str(t).lower().replace(" ", "")) for t in raw_tags]
        tags = list(dict.fromkeys([t for t in tags if len(t) > 2]))
        tags = tags[: band(plat + str(i), rule["tags"][0], rule["tags"][1])]
        cta = pick(ctas, salt, plat, "cta") if not compact else pick(["Save this one.", "More on the blog.", "Go try it."], salt, plat, "scta")
        body = "{b}\n\n{c} {t}".format(b=body, c=cta, t=" ".join(tags))
        if len(body) > rule["max"]:            # hard ceiling, cut on a word boundary
            head = body[: rule["max"] - 4]
            body = head[: head.rfind(" ")].rstrip(",;:") + " …"
        body = _clean_fluff(body)
        opts.append({
            "platform": plat, "text": body, "hook": hook,
            "hashtags": [t.lstrip("#") for t in tags], "chars": len(body), "limit": rule["max"],
            "within_limit": len(body) <= rule["max"], "emoji": len(nlp.EMOJI_RE.findall(body)),
            "score": min(98, 62 + band(plat + str(i), 0, 30)),
            "best_time": pick(["Tue 08:30", "Wed 12:15", "Thu 17:40", "Mon 07:50", "Fri 09:20"], plat),
        })
    joined = "\n\n---\n\n".join(
        "### {p} | {c}/{l} chars\n\n{t}".format(p=o["platform"].upper(), c=o["chars"], l=o["limit"], t=o["text"])
        for o in opts)
    return {"title": "Social set - " + topic, "content": joined,
            "meta": {"options": opts, "platforms": wanted, "tone": ctx["tone"], "topic": topic,
                     "word_count": len(tokenize(joined))}}


# ------------------------------------------------------------------- rewrite
def rewrite(ctx: dict) -> dict:
    src = (ctx["source"] or "").strip()
    if len(tokenize(src)) < 6:
        return {"title": "Rewrite", "content": "", "meta": {"error": "Paste at least a sentence or two to rewrite."}}
    mode = ctx.get("mode") or "tone"
    tone_name = ctx["tone"] if ctx["tone"] in TONE_BANKS else "professional"
    tone = TONE_BANKS[tone_name]
    sents = nlp.sentences(src)
    changes: list[str] = []
    out: list[str] = []

    for s in sents:
        if mode == "concise":
            for phrase, good in (("in order to", "to"), ("due to the fact that", "because"),
                                 ("at this point in time", "now"), ("for the purpose of", "for")):
                new = re.sub(re.escape(phrase), good, s, flags=re.I)
                if new != s:
                    changes.append("\u201c%s\u201d \u2192 \u201c%s\u201d" % (phrase, good))
                    s = new
            s = re.sub(r"\b(very|really|quite|just|actually|basically|essentially|literally)\s+", "", s, flags=re.I)
            s = re.sub(r"\bit is (?:important|worth noting) to note that,?\s*", "", s, flags=re.I)
            if len(tokenize(s)) > 26:
                head, _, tail = s.partition(", and ")
                if not tail:
                    head, _, tail = s.partition(" but ")
                if tail and len(tokenize(head)) > 8:
                    out.append(head.rstrip(",; ") + ".")
                    s = tail[:1].upper() + tail[1:]
        s = FILLER_RE.sub("", s)
        s = re.sub(r"^[,;:\s]+", "", s)
        if mode in ("simplify", "tone"):
            swaps = list(WORD_SWAPS.items()) + list(tone["verb"].items()) if mode == "simplify" else tone["verb"].items()
            for bad, good in swaps:
                pat = re.compile(r"\b" + re.escape(bad) + r"\b", re.I)
                if pat.search(s):
                    s = pat.sub(good, s)
                    changes.append("\u201c%s\u201d \u2192 \u201c%s\u201d" % (bad, good))
        if tone_name == "professional":
            contractions = {"can't": "cannot", "won't": "will not", "don't": "do not", "it's": "it is",
                            "that's": "that is", "you're": "you are", "i'm": "I am", "we'll": "we will",
                            "we're": "we are", "they're": "they are", "isn't": "is not"}
            s = re.sub(r"\b(" + "|".join(contractions) + r")\b", lambda m: contractions[m.group(0).lower()], s, flags=re.I)
            s = re.sub(r"[!?]$", ".", s)
        elif tone_name == "casual":
            for formal, easy in (("it is ", "it's "), ("do not ", "don't "), ("we will ", "we'll "),
                                 ("you are ", "you're ")):
                s = s.replace(formal, easy)
        elif tone_name == "bold":
            s = re.sub(r"\b(maybe|perhaps|might|could|somewhat|kind of|a bit)\b", "will", s, flags=re.I)
            s = re.sub(r"\bi think\b|\bwe believe\b", "", s, flags=re.I)
        s = re.sub(r"\s{2,}", " ", s).strip()
        s = re.sub(r"^([a-z])", lambda m: m.group(1).upper(), s)
        if s and s not in out:
            out.append(s.rstrip(".") + ".")

    if mode == "expand":
        extra = ["Put a number on it: {p}% of teams that track this hit the target early.".format(p=band(ctx["salt"], 12, 48)),
                 "Owner and deadline, in writing - that one habit is where {t} stops slipping.".format(t=ctx["topic"]),
                 "Name the reader's objection before they do; agreement gets faster."]
        out = out[:2] + [extra[0]] + out[2:4] + [extra[1]] + out[4:] + [extra[2]]
    if mode != "concise":
        out.insert(0, pick(tone["open"], ctx["salt"], "open"))
        out.append(tone["close"])

    body = _clean_fluff(" ".join(dict.fromkeys([o for o in out if o])))
    before, after = readability(src), readability(body)
    changes.insert(0, "tone \u2192 " + tone_name)
    diff_words = after["words"] - before["words"]
    changes.insert(1, "{a} \u2192 {b} words ({s}{d})".format(a=before["words"], b=after["words"],
                                                             s="-" if diff_words < 0 else "+", d=abs(diff_words)))
    changes.insert(2, "readability {x} \u2192 {y}".format(x=before["flesch"], y=after["flesch"]))
    kept = round(sum(1 for t in tokenize(body) if t in set(tokenize(src))) / max(1, len(tokenize(body))), 2)
    return {"title": "Rewrite - " + ctx["topic"][:40], "content": body,
            "meta": {"before": before, "after": after, "readability_delta": round(after["flesch"] - before["flesch"], 1),
                     "changes": changes[:10], "mode": mode, "tone": tone_name, "retention": kept,
                     "word_count": after["words"]}}


# -------------------------------------------------------------------- summarize
def _heading_set(raw: str) -> set:
    """Titles, H2s and italic standfirsts are furniture, not content to summarise."""
    def norm(s: str) -> str:
        return re.sub(r"[^a-z0-9 ]", "", (s or "").lower().strip()).strip()
    heads = re.findall(r"^#{1,6}\s*(.+)$", raw or "", re.M)
    italics = re.findall(r"^\s*_([^_\n]{3,200})_\s*$", raw or "", re.M)
    return {norm(h) for h in heads + italics if norm(h)}


def summarize(ctx: dict) -> dict:
    raw_src = (ctx["source"] or "").strip()
    furniture = _heading_set(raw_src)
    src = nlp.strip_md(raw_src).strip()
    if len(tokenize(src)) < 14:
        return {"title": "Summary", "content": "", "meta": {"error": "Paste at least a few sentences to summarise."}}
    def _keep(s: str) -> bool:
        clean = re.sub(r"[^a-z0-9 ]", "", s.lower()).strip()
        if len(tokenize(s)) < 6 or JUNK_LINE.search(s):
            return False
        if clean in furniture:
            return False
        return not any(clean.startswith(h[:40]) for h in furniture if len(h) > 12)

    sents = [s for s in nlp.sentences(src) if _keep(s)]
    if not sents:
        sents = nlp.sentences(src)
    terms = dict(key_terms(src, 4))
    top = list(terms.keys())
    scored = []
    for i, s in enumerate(sents):
        toks = tokenize(s)
        if len(toks) < 5:
            continue
        hits = sum(1 for t in toks if t in top[:18])
        pos_bonus = 1.35 if i < 2 else (1.15 if i >= len(sents) - 2 else 1.0)
        num_bonus = 1.5 if re.search(r"\d", s) else 1.0
        length_pen = 0.6 if len(toks) > 45 else 1.0
        scored.append((hits * pos_bonus * num_bonus * length_pen / math.log(2 + len(toks)), s))
    if not scored:
        scored = [(1.0, sents[0])]
    scored.sort(key=lambda x: -x[0])
    n = {"short": 3, "medium": 5, "long": 8}.get(ctx["length"], 4)
    chosen = {s for _, s in scored[:n]}
    ordered = [s for s in sents if s in chosen] or [scored[0][1]]
    lead = ordered[0]
    numbers = re.findall(r"\$?\d[\d.,]*%?", src)[:3]
    tldr = lead.rstrip(".")[:190] + "." + (" Key numbers: " + ", ".join(numbers) + "." if numbers else "")
    bullets = "\n".join("- " + s for s in ordered)
    actions = [s for s in ordered if re.search(r"\b(must|should|need to|next|plan|ship|review|deadline|assign|by \w+day)\b", s, re.I)]
    stats = readability(src)
    compressed = round(len(tokenize(bullets)) / max(1, stats["words"]), 2)
    out = "**TL;DR** - {t}\n\n**Key points**\n{b}".format(t=tldr, b=bullets)
    if actions:
        out += "\n\n**Action items**\n" + "\n".join("- [ ] " + a for a in actions[:4])
    out += "\n\n_Compressed {w} words to {c} ({p}% shorter).".format(
        w=stats["words"], c=len(tokenize(bullets)), p=max(0, round((1 - compressed) * 100)))
    return {"title": "Summary - " + ctx["topic"][:40], "content": out,
            "meta": {"tldr": tldr, "points": ordered, "actions": actions[:4], "compression": compressed,
                     "keywords": top[:6], "source_stats": stats, "word_count": len(tokenize(out))}}


# ------------------------------------------------------------------------ seo
def seo(ctx: dict) -> dict:
    topic, salt = ctx["topic"], ctx["salt"]
    seed_terms = [t["phrase"] for t in nlp.ngrams(ctx["prompt"] or topic, (1, 3), 8)]
    seeds = list(dict.fromkeys([topic] + seed_terms[:4]))
    modifiers = ["for beginners", "examples", "template", "checklist", "vs", "software", "strategy",
                 "best practices", "guide", "pricing", "alternatives", "for small business", "statistics"]
    intents = ["informational", "commercial", "transactional", "navigational"]
    rows: list[dict] = []
    seen: set[str] = set()
    for base in seeds:
        for m in modifiers:
            kw = ("%s %s" % (base, m)).strip().lower()
            if len(kw) > 62 or kw in seen:
                continue
            seen.add(kw)
            vol = log_scale(kw + salt, 40, 41000)
            diff = band(kw, 6, 78)
            rows.append({"keyword": kw, "volume": vol, "difficulty": diff,
                         "cpc": round(band(kw, 40, 1450) / 100, 2),
                         "intent": pick(intents, kw),
                         "click_pct": band(kw, 22, 74),
                         "priority": round(min(99, (vol ** 0.28) * (100 - diff) / 6 + band(kw, 0, 12)))})
    rows.sort(key=lambda r: -r["priority"])
    rows = rows[:24]
    questions = ["What is %s?" % topic, "How does %s work?" % topic,
                 "Is %s worth it in %s?" % (topic, YEAR), "What tools do I need for %s?" % topic,
                 "How long until %s shows results?" % topic]
    primary = rows[0]["keyword"] if rows else topic
    meta_title = pick([
        "{t}: {n} Proven Steps ({y})".format(t=title_case(primary), n=band(salt, 5, 9), y=YEAR),
        "{t} - Templates, Checklist and Examples".format(t=title_case(topic)),
        "Best {t} Setup in {y} (Free Template)".format(t=title_case(topic), y=YEAR),
    ], salt, "mt")
    meta_desc = "{t}, minus the fluff: a {n}-step {k} workflow, free template and the numbers {a} actually need. {y}.".format(
        t=title_case(topic), n=band(salt, 4, 7), k=primary, a=ctx["audience"], y=YEAR)
    outline = [
        "# " + meta_title,
        "## Why {t} matters in {y}".format(t=topic, y=YEAR) + "  (informational intent)",
        "## " + title_case(primary) + " - definition and scope  (FAQ target)",
        "## Step-by-step workflow + free template  (transactional - CTA above the fold)",
        "## Comparison table: options by price and speed  (featured snippet bait)",
        "## Mistakes that cost teams {n} weeks".format(n=band(salt, 2, 9)),
        "## FAQ  (answer each in 42 words for snippet eligibility)",
        "## CTA: {b} demo  (commercial intent)".format(b=ctx["brand"]),
    ]
    faq_answers = ["Most teams see a measurable difference in 2-4 weeks, provided one person owns the brief.",
                   "It depends on volume: start with one channel and one template, then widen.",
                   "Yes - if you can write the outcome and the number you want to move.",
                   "One template, one review lane, one scorecard. Everything else is optional.",
                   "About a week for the first publishable version, if the brief is done."]
    table = ("\n\n## Keyword targets\n\n| Keyword | Intent | Vol/mo | Difficulty | CPC | Priority |\n"
             "| --- | --- | --- | --- | --- | --- |\n")
    table += "\n".join(
        "| {kw} | {it} | {vol:,} | {dif} | ${cpc} | {pri} |".format(
            kw=r["keyword"], it=r["intent"], vol=r["volume"], dif=r["difficulty"], cpc=r["cpc"], pri=r["priority"])
        for r in rows[:12])
    faq = "\n\n".join("**%s**\n\n%s" % (q, a) for q, a in zip(questions, faq_answers))
    body = "\n".join(outline) + table + "\n\n## FAQ block\n\n" + faq
    score = min(96, 42 + len(rows) // 2 + (12 if len(meta_title) <= 60 else 0) + (10 if len(meta_desc) <= 158 else 0))
    return {"title": "SEO brief - " + topic, "content": _clean_fluff(body),
            "meta": {"keywords": rows, "primary": primary, "total_volume": sum(r["volume"] for r in rows),
                     "meta_title": meta_title, "meta_title_len": len(meta_title),
                     "meta_description": meta_desc.strip(), "meta_desc_len": len(meta_desc.strip()),
                     "outline": outline, "questions": questions, "score": score,
                     "word_target": band(topic, 1100, 2400),
                     "internal_links": ["/templates/" + topic.split()[0].lower(), "/features/blog-writer", "/pricing"],
                     "word_count": len(tokenize(body))}}


# --------------------------------------------------------------------- analyze
def analyze(ctx: dict) -> dict:
    raw = (ctx["source"] or "").strip()
    src = nlp.strip_md(raw)
    toks = tokenize(src)
    if len(toks) < 20:
        return {"title": "Analysis", "content": "", "meta": {"error": "Paste at least 20 words to run the analyzer."}}
    stats = readability(src)
    sents = nlp.sentences(src)
    low = src.lower()
    salt = ctx["salt"]

    flagged = {}
    for label, bank in AI_FLAGS.items():
        found = sorted({w for w in bank if re.search(r"\b" + re.escape(w) + r"\b", low)})
        if found:
            flagged[label] = found
    flag_hits = sum(len(v) for v in flagged.values())
    per_100 = flag_hits / max(1, len(toks)) * 100

    lens = [len(tokenize(s)) for s in sents] or [0]
    mean = sum(lens) / len(lens)
    var = sum((x - mean) ** 2 for x in lens) / max(1, len(lens))
    burstiness = math.sqrt(var) / max(1.0, mean)
    diversity = len(set(toks)) / max(1, len(toks))
    openers = [s.split()[0].lower().strip(",.;:!?") for s in sents if s.split()]
    rep_openers = 1 - len(set(openers)) / max(1, len(openers))
    para_lens = [len(tokenize(x)) for x in re.split(r"\n\s*\n", raw) if x.strip()] or [0]
    if len(para_lens) > 1:
        pm = sum(para_lens) / len(para_lens)
        pvar = sum((x - pm) ** 2 for x in para_lens) / len(para_lens)
        uniform_paras = max(0.0, 1 - math.sqrt(pvar) / max(1.0, pm))
    else:
        uniform_paras = 0.0
    numbers = len(re.findall(r"\d", src)) / max(1, len(sents))
    adverb_heavy = len(re.findall(r"\b(ly)\b", low)) / max(1, len(toks))
    hedges = len(re.findall(r"\b(maybe|perhaps|might|could|somewhat|very|really|just)\b", low)) / max(1, len(sents))

    ai_score = 100.0
    ai_score -= max(0.0, min(60.0, 260.0 * (burstiness - 0.06)))
    ai_score -= max(0.0, min(16.0, 90.0 * (diversity - 0.42)))
    ai_score += max(0.0, min(34.0, 46.0 * (per_100 - 0.9)))
    ai_score += max(0.0, min(16.0, 60.0 * (uniform_paras - 0.62)))
    ai_score += max(0.0, min(10.0, 30.0 * (rep_openers - 0.5)))
    ai_score = round(max(2.0, min(99.0, ai_score)), 1)
    human_score = round(100 - ai_score, 1)

    pos = sum(1 for t in toks if t in POSITIVE)
    neg = sum(1 for t in toks if t in NEGATIVE)
    sentiment = "positive" if pos > neg * 1.4 else ("negative" if neg > pos * 1.4 else "neutral")
    tone_scores = {}
    for name, bank in TONE_BANKS.items():
        sc = sum(1 for w in bank["verb"] if re.search(r"\b" + re.escape(w) + r"\b", low))
        sc += sum(2 for o in bank["open"] if o.lower().strip(":,-") in low)
        tone_scores[name] = sc
    detected_tone = max(tone_scores.items(), key=lambda kv: kv[1])[0] if max(tone_scores.values()) > 0 else "neutral"

    density = [{"term": t, "count": c, "pct": round(c / max(1, len(toks)) * 100, 2)} for t, c in key_terms(src, 4)[:8]]
    structure = {"headings": len(re.findall(r"^#{1,6} ", raw, re.M)),
                 "lists": len(re.findall(r"^\s*(?:[-*]|\d+\.)\s", src, re.M)),
                 "table_rows": len(re.findall(r"^\|", raw, re.M)),
                 "links": len(re.findall(r"\[[^\]]+\]\([^)]+\)", raw)),
                 "images": len(re.findall(r"!\[[^\]]*\]\(", raw)),
                 "avg_sentence_words": round(mean, 1), "longest_sentence": max(lens)}

    fixes = []
    if per_100 > 1.1:
        flat = [w for v in flagged.values() for w in v]
        fixes.append({"issue": "AI-tell vocabulary", "impact": "high",
                      "detail": "%d flagged words (%s). Swap them for concrete verbs and objects." % (
                          len(flat), ", ".join(flat[:6]) or "none")})
    if burstiness < 0.28:
        fixes.append({"issue": "Metronome sentence lengths", "impact": "high",
                      "detail": "Sentence length variation is %.2f (sigma/mean). Follow a 30-word sentence with a 6-word one." % burstiness})
    if stats["flesch"] < 45:
        fixes.append({"issue": "Dense prose", "impact": "medium",
                      "detail": "Flesch %.1f is about grade %.1f. Aim for 60+ for %s." % (stats["flesch"], stats["grade"], ctx["audience"])})
    if uniform_paras > 0.75:
        fixes.append({"issue": "Uniform paragraph blocks", "impact": "medium",
                      "detail": "Every block is the same size. Turn one into a single-line punch or a list."})
    if numbers < 0.35:
        fixes.append({"issue": "No proof", "impact": "high",
                      "detail": "%.2f numerals per sentence. Add one number per section or drop the claim." % numbers})
    if rep_openers > 0.45:
        fixes.append({"issue": "Repeated sentence openers", "impact": "medium",
                      "detail": "%d%% of sentences start with the same word." % round(rep_openers * 100)})
    if hedges > 0.5:
        fixes.append({"issue": "Hedging language", "impact": "low",
                      "detail": "Cut maybe / might / could. Definite claims age better."})
    if structure["headings"] < max(1, len(sents) // 12):
        fixes.append({"issue": "Thin structure", "impact": "low",
                      "detail": "Add an H2 every 3-4 paragraphs so readers can scan and skip."})
    if not fixes:
        fixes.append({"issue": "Nothing structural to fix", "impact": "none",
                      "detail": "Rhythm, proof and readability are healthy. Ship it."})

    projected = {}
    if fixes:
        projected = {"readability": round(min(92, stats["flesch"] + 9 + len(fixes) * 1.4), 1),
                     "human_score": round(min(99, human_score + sum(4 for f in fixes if f["impact"] == "high")
                                              + sum(2 for f in fixes if f["impact"] == "medium")), 1)}

    content_score = round(max(3, min(99,
        0.34 * stats["flesch"]
        + 0.24 * human_score
        + 0.16 * min(100, numbers * 60 + 40)
        + 0.14 * min(100, 40 + structure["headings"] * 14 + structure["lists"] * 10)
        + 0.12 * min(100, diversity * 130))), 0)
    verdict = ("Publish as-is" if content_score >= 82 and ai_score < 30 else
               "Light edit" if content_score >= 68 else
               "Rewrite pass recommended" if content_score >= 52 else "Rebuild from outline")
    bars = [
        {"label": "Readability", "value": int(min(100, stats["flesch"]))},
        {"label": "Human rhythm", "value": int(min(100, burstiness * 190))},
        {"label": "Lexical variety", "value": int(min(100, diversity * 120))},
        {"label": "Proof density", "value": int(min(100, 40 + numbers * 55))},
        {"label": "Structure", "value": int(min(100, 40 + structure["headings"] * 12 + structure["lists"] * 6))},
        {"label": "Original phrasing", "value": int(max(8, 100 - per_100 * 26))},
    ]
    lines = ["# Content report - " + ctx["topic"][:36], "",
             "**Overall %d/100** | verdict: %s" % (content_score, verdict),
             "- AI-generated likelihood: **%s%%** (human fingerprint %s%%)" % (ai_score, human_score),
             "- Readability: Flesch %.1f | grade %.1f | %d words | %d min" % (
                 stats["flesch"], stats["grade"], stats["words"], stats["reading_time_min"]),
             "- Tone: %s | sentiment: %s" % (detected_tone, sentiment),
             "", "## Signal breakdown", ""]
    lines += ["- %s: %d/100" % (b["label"], b["value"]) for b in bars]
    lines += ["", "## Fixes worth the time", ""]
    lines += ["1. **%s** (%s) - %s" % (f["issue"], f["impact"], f["detail"]) for f in fixes]
    if projected:
        lines += ["", "## Projected after fixes", "",
                  "- Readability %.1f -> %s" % (stats["flesch"], projected["readability"]),
                  "- Human fingerprint %s%% -> %s%%" % (human_score, projected["human_score"])]
    lines += ["", "_Analysed %d sentences, %d words | engine build %s_" % (len(sents), len(toks), salt[:6])]
    return {"title": "Content report - " + ctx["topic"][:40], "content": "\n".join(lines),
            "meta": {"content_score": content_score, "ai_probability": ai_score, "human_score": human_score,
                     "readability": stats, "tone": detected_tone, "sentiment": sentiment,
                     "keyword_density": density, "flags": flagged, "per_100_words": round(per_100, 2),
                     "burstiness": round(burstiness, 3), "lexical_diversity": round(diversity, 3),
                     "structure": structure, "metrics": bars, "fixes": fixes, "verdict": verdict,
                     "projected": projected, "word_count": stats["words"]}}


DISPATCH = {"blog": blog, "text": text, "caption": caption, "rewrite": rewrite,
            "summarize": summarize, "seo": seo, "analyze": analyze}
CREDITS = {"blog": 12, "text": 4, "caption": 3, "rewrite": 3, "summarize": 2, "seo": 5, "analyze": 2}
MODELS = {"blog": "nebula-longform-3", "text": "nebula-copy-2", "caption": "nebula-social-2",
          "rewrite": "nebula-edit-2", "summarize": "nebula-edit-2", "seo": "nebula-serp-1",
          "analyze": "nebula-insight-1"}


def run(kind: str, params: dict) -> dict:
    if kind not in DISPATCH:
        raise ValueError("unknown generation kind: %s" % kind)
    ctx = _norm(params)
    result = DISPATCH[kind](ctx)
    chars_in = len((params.get("source") or params.get("prompt") or ""))
    latency = band("%s|%s" % (kind, ctx["salt"]), 240, 1400) + int(chars_in * 0.35)
    return {
        "kind": kind,
        "title": result["title"],
        "content": result["content"],
        "meta": result["meta"],
        "engine": {"model": MODELS[kind], "credits": CREDITS[kind], "latency_ms": latency,
                   "words_out": len(tokenize(result["content"])), "chars_in": chars_in,
                   "temperature": params.get("temperature", 0.7), "seed": int(dice(ctx["salt"], kind) * 99999),
                   "mode": "local-engine"},
    }


def estimate(kind: str, params: dict) -> dict:
    """Pre-flight cost + time estimate shown in the composer."""
    chars = len((params.get("source") or params.get("prompt") or ""))
    target = _len_words(params.get("length") or "medium")
    secs = round((band(kind, 320, 1500) + chars * 0.35) / 1000, 1)
    words = target if kind in ("blog", "text") else max(40, int(chars * 0.35))
    if kind in ("summarize", "analyze") and chars:
        words = {"short": 60, "medium": 120, "long": 200}.get(params.get("length") or "medium", 120)
    return {"kind": kind, "credits": CREDITS.get(kind, 3), "seconds": secs,
            "expected_words": words, "model": MODELS.get(kind, "nebula-copy-2")}
